### ISSUE TITLE
Add dark theme to CSS

### ISSUE THREAD

**Issue by vitaly-zdanevich** [vim-awesome/vim-awesome#400]
Through [prefers-color-scheme](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme).

**Comment by mboyakanni** [comment]
You can add it using this:
```css
@media (prefers-color-scheme: dark) {
        h1,
        p,
        div {
          color: white;
        }
        div {
          background-color: black;
        }
      }
  
      @media (prefers-color-scheme: light) {
        h1,
        p,
        div {
          color: black;
        }
        div {
          background-color: white;
        }
      }
```
